### ISSUE TITLE
不同loss的权重问题

### ISSUE THREAD

**Issue by LiangbinXie** [jzijin/Super-FAN#8]
我看论文中并没有提及不同loss之间设置的权重，请问你是依据什么设置那些权重的呢？

**Comment by jzijin** [comment]
> 我看论文中并没有提及不同loss之间设置的权重，请问你是依据什么设置那些权重的呢？

参考其他论文设置。若觉得训练效果不佳，可将这几个参数改成超参数，改变参数值训练。mmsr这个项目很不错，通过更改yaml配置文件就可以改变参数。建议将其当做框架，然后可以将自己的模型添加进去训练。

**Comment by LiangbinXie** [comment]
好的，谢谢
